apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-

spec:
  entrypoint: hello-i18n

  arguments:
    parameters:
    - name: message
      value: "hello hi"

  templates:
  - name: hello-i18n
    steps:
    - - name: greet-en
        template: say-hello
        arguments:
          parameters:
          - name: message
            value: "hello"
          
      - name: greet-fr
        template: say-hello
        arguments:
          parameters:
          - name: message
            value: "bonjour"

      - name: greet-es
        template: say-hello
        arguments:
          parameters:
          - name: message
            value: "hola"


  - name: say-hello
    inputs:
      parameters:
      - name: message
    container:
      image: alpine
      command: [ "echo" ]
      args: [ "{{inputs.parameters.message}}" ]
   
