apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-

spec:
  entrypoint: hello-i18n

  templates:
  - name: hello-i18n
    steps:
    - - name: greet
        template: say-hello
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:
          - hello
          - bonjour
          - hallo
          - zdravo
          - merhaba
          - привет
          - سلام
          - 你好
          - हैलो

  - name: say-hello
    inputs:
      parameters:
      - name: message
    container:
      image: alpine
      command: [ "echo" ]
      args: [ "{{inputs.parameters.message}}" ]
