apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-

spec:
  entrypoint: say-hello

  arguments:
    parameters:
    - name: message
      value: "hello hi"

  templates:
  - name: say-hello
    container:
      image: docker/whalesay
      command: [ "cowsay" ]
      args: [ "{{workflow.parameters.message}}" ]
